### PR TITLE
First cut of a modular tracer structure

### PR DESCRIPTION
**Pull request by toru**
Implement an intermediate tracer representation in C, so that we can cleanly implement multiple tracers (e.g. http and quic).

### CODE REVIEW

**Comment by gfx** [comment]
👍

**Comment by toru** [comment]
Thanks! I have one more commit coming that moves the probe initialization routine to the tracer.

**Comment by toru** [comment]
Heh, apparently my libbcc doesn't have the `ok()` helper. Thanks for motivating me to update.

**Comment by toru** [comment]
@gfx Ugh, sorry, I also realized that my latest commit canceled your nicer USDT initialization code. I'll add another commit in a moment.

**Comment by gfx** [comment]
Oh, I see. Now I'm working on adding iovisor/bcc as a submodule. It should solve a lot.

**Comment by toru** [comment]
That would be lovely. I think I've done everything I want to do in this PR. Are you going to add a submodule in this branch, or do you have your own branch to submit against `v2`?

**Comment by gfx** [comment]
Not in this branch. I'll make pull-reqs to `v2` to avoid conflicts.

**Comment by gfx** [comment]
So please merge it to `v2`.

**Comment by toru** [comment]
Sounds good! I'm looking forward to it.

**Pull request merged**
