### PR TITLE
add "time-nanosec" field for nanosecond-resolution time

### PR DESCRIPTION
**Pull request by gfx**
The current "time" field is millisecond-resolution, but it is not correctly sortable. Also, [qlog](https://github.com/quiclog/internet-drafts) can deal with usec resolution, so it is useful to provide hi-resolution time for later analysis.

I'd like to keep the "time" field for compatibility with other tools that use quicly probes directly: https://github.com/h2o/quicly/tree/master/misc

### CODE REVIEW

**Comment by gfx** [comment]
Changed names as https://github.com/h2o/h2o/pull/2053#discussion_r283580474 suggested.

**Comment by gfx** [comment]
I already use `clock_gettime(CLOCK_REALTIME, ...)` here 😉

**Comment by gfx** [comment]
@syohex san suggested we can use C++ standard library for this purpose. https://twitter.com/syohex/status/1253527261896032256

**Comment by toru** [comment]
I think this PR as-is because it's an idiomatic use of the POSIX clock_gettime(). That said, this is a very hot code path -- if std::chrono gives us perf benefits, I have no objections to using it.

**Comment by syohex** [comment]
> If std::chrono gives us perf benefit

I suppose there is no performance benefit. Because std::chrono API is only wrapper function of `clock_gettime` on Unix like system. For example `std::chrono::system_clock::now` implementation is below. This increases some function/constructor calls overhead. I suppose they are inlined by compiler optimization however more instructions are necessary rather than calling `clock_gettime` directly.

```c++
  struct timespec tp;
  if (0 != clock_gettime(CLOCK_REALTIME, &tp))
    __throw_system_error(errno, "clock_gettime(CLOCK_REALTIME) failed");
  return time_point(seconds(tp.tv_sec) + microseconds(tp.tv_nsec / 1000));
```

**Comment by toru** [comment]
Skew from not using the server time does sound real. This brings up another topic that it looks like we stopped using quicly's at/time value at some point.

**Comment by toru** [comment]
Please dismiss my comment from above. We do use `at` where possible from quicly. I had forgotten that there are non-quicly probes in the QUIC tracer.

**Comment by gfx** [comment]
Thanks to @kazuho, I've realized there are two problems with this PR:

1. `CLOCK_REALTIME` is not suitable to keep the exact order, so we have to use another stuff for sorting
2. `CLOCK_REALTIME` is not what exactly quicly emits, so we have to use `at` field as a timestamp

Considering another way.

**Pull request closed without merging**
